# 基础镜像
FROM redis:7.2.4-alpine

# 挂载目录
VOLUME /home/financial-backend/redis
# 创建目录
RUN mkdir -p /home/financial-backend/redis
# 指定路径
WORKDIR /home/financial-backend/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/financial-backend/redis/redis.conf
