# 基础镜像
FROM  openjdk:17-oracle

# 挂载目录
VOLUME /home/financial-backend
# 创建目录
RUN mkdir -p /home/financial-backend
# 指定路径
WORKDIR /home/financial-backend
# 复制jar文件到路径
COPY ./jar/financial-backend-modules-file.jar /home/financial-backend/financial-backend-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","financial-backend-modules-file.jar"]