# 基础镜像
FROM nginx

# 挂载目录
VOLUME /home/financial-backend/projects/financial-backend-ui
# 创建目录
RUN mkdir -p /home/financial-backend/projects/financial-backend-ui
# 指定路径
WORKDIR /home/financial-backend/projects/financial-backend-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/financial-backend/projects/financial-backend-ui
