# 基础镜像
FROM  openjdk:17-jdk

# 挂载目录
VOLUME /home/financial-backend
# 创建目录
RUN mkdir -p /home/financial-backend
# 指定路径
WORKDIR /home/financial-backend
# 复制jar文件到路径
COPY ./jar/financial-auth.jar /home/financial-backend/financial-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","financial-auth.jar"]